// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgAutoposter.Infrastructure.Persistence;

#nullable disable

namespace TgAutoposter.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619145241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TgAutoposter.Domain.Ai.AiUsageRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CompletionTokens")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PromptTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal?>("ProviderCostAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("ProviderCostCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("RequestMetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("TaskType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TotalTokens")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("ChannelId", "CreatedAtUtc");

                    b.ToTable("AiUsageRecords");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DetailsJson")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("ChannelId", "CreatedAtUtc");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BotTokenSecretName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DailyAiBudgetLimit")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int>("DailyPostLimit")
                        .HasColumnType("integer");

                    b.Property<string>("DefaultModerationMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Positioning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StyleGuide")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramChatId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUsername");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.ChannelRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserAccountId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserAccountId");

                    b.HasIndex("ChannelId", "UserAccountId", "Role")
                        .IsUnique();

                    b.ToTable("ChannelRoles");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.FooterLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PublicationKindsCsv")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("FooterLinks");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.PublicationTypeSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanUseSourceImage")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FactCheckMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FooterTemplate")
                        .HasColumnType("text");

                    b.Property<decimal>("FrequencyPerDay")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("HeaderTemplate")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxTextLength")
                        .HasColumnType("integer");

                    b.Property<string>("MediaMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModerationMode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresFactCheck")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequiresPoster")
                        .HasColumnType("boolean");

                    b.Property<string>("RumorPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextTemplate")
                        .HasColumnType("text");

                    b.Property<string>("TimeWindowsJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "Kind")
                        .IsUnique();

                    b.ToTable("PublicationTypes");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.ScheduleWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowBreakingNewsBypass")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<int>("MinimumIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.ToTable("ScheduleWindows");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<long?>("TelegramUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("TelegramUsername")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasFilter("\"TelegramUserId\" IS NOT NULL");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Posts.ModerationMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChatId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ImageMessageId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Resolution")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TextMessageId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "IsActive");

                    b.ToTable("ModerationMessages");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Posts.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CostAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("CostCurrency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeduplicationSummary")
                        .HasColumnType("text");

                    b.Property<string>("FactCheckStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FactCheckSummary")
                        .HasColumnType("text");

                    b.Property<string>("FinalText")
                        .HasColumnType("text");

                    b.Property<string>("Footer")
                        .HasColumnType("text");

                    b.Property<string>("GeneratedText")
                        .HasColumnType("text");

                    b.Property<string>("Header")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("MediaUrlsJson")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("OriginalSummary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("PublicationKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PublicationTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RejectedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text");

                    b.Property<string>("RelatedSourcesJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ScheduledForUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourceCandidateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramMessageId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("TelegramPostUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("PublicationTypeId");

                    b.HasIndex("RejectedByUserId");

                    b.HasIndex("SourceCandidateId");

                    b.HasIndex("SourceId");

                    b.HasIndex("SourceUrl");

                    b.HasIndex("ChannelId", "Status", "ScheduledForUtc");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Posts.PostVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uuid");

                    b.Property<string>("Prompt")
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PostId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("PostVersions");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Sources.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowNsfw")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowRumors")
                        .HasColumnType("boolean");

                    b.Property<string>("AllowedPublicationKindsCsv")
                        .HasColumnType("text");

                    b.Property<string>("BlacklistKeywordsCsv")
                        .HasColumnType("text");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<int>("CheckEveryMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastCheckedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinimumComments")
                        .HasColumnType("integer");

                    b.Property<int>("MinimumScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RedditListing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RedditTopPeriod")
                        .HasColumnType("text");

                    b.Property<string>("Subreddit")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("WhitelistKeywordsCsv")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId", "Kind", "Subreddit");

                    b.ToTable("Sources");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Sources.SourceCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CommentsCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FoundAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsConsumed")
                        .HasColumnType("boolean");

                    b.Property<string>("MediaUrlsJson")
                        .HasColumnType("text");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("RawText")
                        .HasColumnType("text");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTimeOffset?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.HasIndex("ChannelId", "NormalizedHash")
                        .IsUnique();

                    b.ToTable("SourceCandidates");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Ai.AiUsageRecord", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Channels.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TgAutoposter.Domain.Posts.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Channel");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Audit.AuditLog", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Channels.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TgAutoposter.Domain.Channels.UserAccount", "UserAccount")
                        .WithMany()
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Channel");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.ChannelRole", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Channels.Channel", "Channel")
                        .WithMany("Roles")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TgAutoposter.Domain.Channels.UserAccount", "UserAccount")
                        .WithMany("Roles")
                        .HasForeignKey("UserAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.FooterLink", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Channels.Channel", "Channel")
                        .WithMany("FooterLinks")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.PublicationTypeSetting", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Channels.Channel", "Channel")
                        .WithMany("PublicationTypes")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.ScheduleWindow", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Channels.Channel", "Channel")
                        .WithMany("ScheduleWindows")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Posts.ModerationMessage", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Posts.Post", "Post")
                        .WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Posts.Post", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Channels.UserAccount", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TgAutoposter.Domain.Channels.Channel", "Channel")
                        .WithMany("Posts")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TgAutoposter.Domain.Channels.PublicationTypeSetting", "PublicationType")
                        .WithMany()
                        .HasForeignKey("PublicationTypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TgAutoposter.Domain.Channels.UserAccount", "RejectedByUser")
                        .WithMany()
                        .HasForeignKey("RejectedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TgAutoposter.Domain.Sources.SourceCandidate", "SourceCandidate")
                        .WithMany()
                        .HasForeignKey("SourceCandidateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TgAutoposter.Domain.Sources.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Channel");

                    b.Navigation("PublicationType");

                    b.Navigation("RejectedByUser");

                    b.Navigation("Source");

                    b.Navigation("SourceCandidate");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Posts.PostVersion", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Posts.Post", "Post")
                        .WithMany("Versions")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Sources.Source", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Channels.Channel", "Channel")
                        .WithMany("Sources")
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Sources.SourceCandidate", b =>
                {
                    b.HasOne("TgAutoposter.Domain.Channels.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TgAutoposter.Domain.Sources.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Channel");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.Channel", b =>
                {
                    b.Navigation("FooterLinks");

                    b.Navigation("Posts");

                    b.Navigation("PublicationTypes");

                    b.Navigation("Roles");

                    b.Navigation("ScheduleWindows");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Channels.UserAccount", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("TgAutoposter.Domain.Posts.Post", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
